// This file is @generated by prost-build.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct TargetUser {
    #[prost(oneof = "target_user::User", tags = "1")]
    pub user: ::core::option::Option<target_user::User>,
}
/// Nested message and enum types in `TargetUser`.
pub mod target_user {
    #[derive(Clone, PartialEq, Eq, Hash, ::prost::Oneof)]
    pub enum User {
        #[prost(string, tag = "1")]
        UserToken(::prost::alloc::string::String),
    }
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct HealthCheckRequest {}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct HealthCheckResponse {
    #[prost(string, tag = "1")]
    pub status: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct StartAuthSessionRequest {
    #[prost(string, tag = "1")]
    pub client_state: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct StartAuthSessionResponse {
    #[prost(string, tag = "1")]
    pub session_code: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub login_url: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct GetAuthSessionRequest {
    #[prost(string, tag = "1")]
    pub session_code: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub client_state: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct GetAuthSessionResponse {
    #[prost(message, optional, tag = "1")]
    pub user_token: ::core::option::Option<UserToken>,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct RefreshAuthSessionRequest {}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct RefreshAuthSessionResponse {
    #[prost(message, optional, tag = "1")]
    pub user_token: ::core::option::Option<UserToken>,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct RevokeAuthSessionRequest {}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct RevokeAuthSessionResponse {}
/// Verify the target is compliant with the given Product Name as registered in `ucs-auth-api` config
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct VerifyCompliance {
    #[prost(string, tag = "1")]
    pub product_name: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct VerifyRequirement {
    #[prost(oneof = "verify_requirement::Requirement", tags = "2")]
    pub requirement: ::core::option::Option<verify_requirement::Requirement>,
}
/// Nested message and enum types in `VerifyRequirement`.
pub mod verify_requirement {
    #[derive(Clone, PartialEq, Eq, Hash, ::prost::Oneof)]
    pub enum Requirement {
        #[prost(message, tag = "2")]
        Compliance(super::VerifyCompliance),
    }
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct VerifyUserRequest {
    #[prost(message, optional, tag = "1")]
    pub target_user: ::core::option::Option<TargetUser>,
    #[prost(message, repeated, tag = "2")]
    pub requirements: ::prost::alloc::vec::Vec<VerifyRequirement>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct VerifyUserResponse {
    #[prost(message, optional, tag = "1")]
    pub user_info: ::core::option::Option<UserInfo>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ExchangeExternalTokenForUserTokenRequest {
    #[prost(string, tag = "1")]
    pub external_token: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub token_type: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ExchangeExternalTokenForUserTokenResponse {
    #[prost(message, optional, tag = "1")]
    pub user_token: ::core::option::Option<UserToken>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ExchangeApiKeyForUserTokenRequest {
    #[prost(string, tag = "1")]
    pub api_key: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ExchangeApiKeyForUserTokenResponse {
    #[prost(message, optional, tag = "1")]
    pub user_token: ::core::option::Option<UserToken>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct UserToken {
    #[prost(string, tag = "1")]
    pub user_token: ::prost::alloc::string::String,
    /// Epoch
    #[prost(int64, tag = "2")]
    pub expires_at: i64,
    /// URC user ID
    #[prost(string, tag = "3")]
    pub user_id: ::prost::alloc::string::String,
    /// Display name
    #[prost(string, tag = "4")]
    pub user_name: ::prost::alloc::string::String,
    /// Opaque rotating refresh credential; only present on auth-session creation/refresh
    #[prost(string, optional, tag = "5")]
    pub refresh_token: ::core::option::Option<::prost::alloc::string::String>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ResourcePermission {
    #[prost(string, tag = "1")]
    pub resource_id: ::prost::alloc::string::String,
    #[prost(string, repeated, tag = "2")]
    pub permission: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ExchangeUserTokenForMultiresourceTokenRequest {
    #[prost(string, repeated, tag = "1")]
    pub resource_id: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ExchangeUserTokenForMultiresourceTokenResponse {
    #[prost(message, optional, tag = "1")]
    pub token: ::core::option::Option<UserToken>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct CheckUserPermissionRequest {
    #[prost(string, repeated, tag = "1")]
    pub resource_id: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    #[prost(message, optional, tag = "2")]
    pub target_user: ::core::option::Option<TargetUser>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct CheckUserPermissionResponse {
    #[prost(message, repeated, tag = "1")]
    pub allowed_resource_permission: ::prost::alloc::vec::Vec<ResourcePermission>,
    #[prost(message, repeated, tag = "2")]
    pub denied_resource_permission: ::prost::alloc::vec::Vec<ResourcePermission>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct LookupUserPermissionsRequest {
    #[prost(string, tag = "1")]
    pub resource_filter: ::prost::alloc::string::String,
    #[prost(string, optional, tag = "2")]
    pub context_filter: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(int32, optional, tag = "3")]
    pub page_size: ::core::option::Option<i32>,
    #[prost(string, optional, tag = "4")]
    pub page_token: ::core::option::Option<::prost::alloc::string::String>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct LookupUserPermissionsResponse {
    #[prost(message, repeated, tag = "1")]
    pub resource_permission: ::prost::alloc::vec::Vec<ResourcePermission>,
    #[prost(string, optional, tag = "2")]
    pub next_page_token: ::core::option::Option<::prost::alloc::string::String>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct GetUserInfoRequest {
    #[prost(string, tag = "1")]
    pub resource_id: ::prost::alloc::string::String,
    #[prost(string, repeated, tag = "2")]
    pub user_id: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct UserInfo {
    #[prost(string, tag = "1")]
    pub user_id: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub display_name: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetUserInfoResponse {
    #[prost(message, repeated, tag = "1")]
    pub user_info: ::prost::alloc::vec::Vec<UserInfo>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct GetUserIdRequest {
    #[prost(string, tag = "1")]
    pub resource_id: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub user_display_name: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct GetUserIdResponse {
    #[prost(message, optional, tag = "1")]
    pub user_info: ::core::option::Option<UserInfo>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct GetProviderUserIdRequest {
    #[prost(string, tag = "1")]
    pub user_id: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct GetProviderUserIdResponse {
    #[prost(string, tag = "1")]
    pub user_id: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub provider_user_id: ::prost::alloc::string::String,
}
/// Generated client implementations.
pub mod urc_auth_api_client {
    #![allow(
        unused_variables,
        dead_code,
        missing_docs,
        clippy::wildcard_imports,
        clippy::let_unit_value,
    )]
    use tonic::codegen::*;
    use tonic::codegen::http::Uri;
    #[derive(Debug, Clone)]
    pub struct UrcAuthApiClient<T> {
        inner: tonic::client::Grpc<T>,
    }
    impl UrcAuthApiClient<tonic::transport::Channel> {
        /// Attempt to create a new client by connecting to a given endpoint.
        pub async fn connect<D>(dst: D) -> Result<Self, tonic::transport::Error>
        where
            D: TryInto<tonic::transport::Endpoint>,
            D::Error: Into<StdError>,
        {
            let conn = tonic::transport::Endpoint::new(dst)?.connect().await?;
            Ok(Self::new(conn))
        }
    }
    impl<T> UrcAuthApiClient<T>
    where
        T: tonic::client::GrpcService<tonic::body::Body>,
        T::Error: Into<StdError>,
        T::ResponseBody: Body<Data = Bytes> + std::marker::Send + 'static,
        <T::ResponseBody as Body>::Error: Into<StdError> + std::marker::Send,
    {
        pub fn new(inner: T) -> Self {
            let inner = tonic::client::Grpc::new(inner);
            Self { inner }
        }
        pub fn with_origin(inner: T, origin: Uri) -> Self {
            let inner = tonic::client::Grpc::with_origin(inner, origin);
            Self { inner }
        }
        pub fn with_interceptor<F>(
            inner: T,
            interceptor: F,
        ) -> UrcAuthApiClient<InterceptedService<T, F>>
        where
            F: tonic::service::Interceptor,
            T::ResponseBody: Default,
            T: tonic::codegen::Service<
                http::Request<tonic::body::Body>,
                Response = http::Response<
                    <T as tonic::client::GrpcService<tonic::body::Body>>::ResponseBody,
                >,
            >,
            <T as tonic::codegen::Service<
                http::Request<tonic::body::Body>,
            >>::Error: Into<StdError> + std::marker::Send + std::marker::Sync,
        {
            UrcAuthApiClient::new(InterceptedService::new(inner, interceptor))
        }
        /// Compress requests with the given encoding.
        ///
        /// This requires the server to support it otherwise it might respond with an
        /// error.
        #[must_use]
        pub fn send_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.inner = self.inner.send_compressed(encoding);
            self
        }
        /// Enable decompressing responses.
        #[must_use]
        pub fn accept_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.inner = self.inner.accept_compressed(encoding);
            self
        }
        /// Limits the maximum size of a decoded message.
        ///
        /// Default: `4MB`
        #[must_use]
        pub fn max_decoding_message_size(mut self, limit: usize) -> Self {
            self.inner = self.inner.max_decoding_message_size(limit);
            self
        }
        /// Limits the maximum size of an encoded message.
        ///
        /// Default: `usize::MAX`
        #[must_use]
        pub fn max_encoding_message_size(mut self, limit: usize) -> Self {
            self.inner = self.inner.max_encoding_message_size(limit);
            self
        }
        pub async fn health_check(
            &mut self,
            request: impl tonic::IntoRequest<super::HealthCheckRequest>,
        ) -> std::result::Result<
            tonic::Response<super::HealthCheckResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic_prost::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/epic_urc.UrcAuthApi/HealthCheck",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("epic_urc.UrcAuthApi", "HealthCheck"));
            self.inner.unary(req, path, codec).await
        }
        pub async fn start_auth_session(
            &mut self,
            request: impl tonic::IntoRequest<super::StartAuthSessionRequest>,
        ) -> std::result::Result<
            tonic::Response<super::StartAuthSessionResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic_prost::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/epic_urc.UrcAuthApi/StartAuthSession",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("epic_urc.UrcAuthApi", "StartAuthSession"));
            self.inner.unary(req, path, codec).await
        }
        pub async fn get_auth_session(
            &mut self,
            request: impl tonic::IntoRequest<super::GetAuthSessionRequest>,
        ) -> std::result::Result<
            tonic::Response<super::GetAuthSessionResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic_prost::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/epic_urc.UrcAuthApi/GetAuthSession",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("epic_urc.UrcAuthApi", "GetAuthSession"));
            self.inner.unary(req, path, codec).await
        }
        pub async fn refresh_auth_session(
            &mut self,
            request: impl tonic::IntoRequest<super::RefreshAuthSessionRequest>,
        ) -> std::result::Result<
            tonic::Response<super::RefreshAuthSessionResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic_prost::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/epic_urc.UrcAuthApi/RefreshAuthSession",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("epic_urc.UrcAuthApi", "RefreshAuthSession"));
            self.inner.unary(req, path, codec).await
        }
        pub async fn revoke_auth_session(
            &mut self,
            request: impl tonic::IntoRequest<super::RevokeAuthSessionRequest>,
        ) -> std::result::Result<
            tonic::Response<super::RevokeAuthSessionResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic_prost::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/epic_urc.UrcAuthApi/RevokeAuthSession",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("epic_urc.UrcAuthApi", "RevokeAuthSession"));
            self.inner.unary(req, path, codec).await
        }
        pub async fn verify_user(
            &mut self,
            request: impl tonic::IntoRequest<super::VerifyUserRequest>,
        ) -> std::result::Result<
            tonic::Response<super::VerifyUserResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic_prost::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/epic_urc.UrcAuthApi/VerifyUser",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("epic_urc.UrcAuthApi", "VerifyUser"));
            self.inner.unary(req, path, codec).await
        }
        /// For external authentication token login
        pub async fn exchange_external_token_for_user_token(
            &mut self,
            request: impl tonic::IntoRequest<
                super::ExchangeExternalTokenForUserTokenRequest,
            >,
        ) -> std::result::Result<
            tonic::Response<super::ExchangeExternalTokenForUserTokenResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic_prost::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/epic_urc.UrcAuthApi/ExchangeExternalTokenForUserToken",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new(
                        "epic_urc.UrcAuthApi",
                        "ExchangeExternalTokenForUserToken",
                    ),
                );
            self.inner.unary(req, path, codec).await
        }
        /// For API key login
        pub async fn exchange_api_key_for_user_token(
            &mut self,
            request: impl tonic::IntoRequest<super::ExchangeApiKeyForUserTokenRequest>,
        ) -> std::result::Result<
            tonic::Response<super::ExchangeApiKeyForUserTokenResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic_prost::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/epic_urc.UrcAuthApi/ExchangeAPIKeyForUserToken",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new("epic_urc.UrcAuthApi", "ExchangeAPIKeyForUserToken"),
                );
            self.inner.unary(req, path, codec).await
        }
        /// For token exchange
        pub async fn exchange_user_token_for_multiresource_token(
            &mut self,
            request: impl tonic::IntoRequest<
                super::ExchangeUserTokenForMultiresourceTokenRequest,
            >,
        ) -> std::result::Result<
            tonic::Response<super::ExchangeUserTokenForMultiresourceTokenResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic_prost::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/epic_urc.UrcAuthApi/ExchangeUserTokenForMultiresourceToken",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new(
                        "epic_urc.UrcAuthApi",
                        "ExchangeUserTokenForMultiresourceToken",
                    ),
                );
            self.inner.unary(req, path, codec).await
        }
        /// For permission checks
        pub async fn check_user_permission(
            &mut self,
            request: impl tonic::IntoRequest<super::CheckUserPermissionRequest>,
        ) -> std::result::Result<
            tonic::Response<super::CheckUserPermissionResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic_prost::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/epic_urc.UrcAuthApi/CheckUserPermission",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("epic_urc.UrcAuthApi", "CheckUserPermission"));
            self.inner.unary(req, path, codec).await
        }
        pub async fn lookup_user_permissions(
            &mut self,
            request: impl tonic::IntoRequest<super::LookupUserPermissionsRequest>,
        ) -> std::result::Result<
            tonic::Response<super::LookupUserPermissionsResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic_prost::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/epic_urc.UrcAuthApi/LookupUserPermissions",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("epic_urc.UrcAuthApi", "LookupUserPermissions"));
            self.inner.unary(req, path, codec).await
        }
        /// User metadata
        pub async fn get_user_info(
            &mut self,
            request: impl tonic::IntoRequest<super::GetUserInfoRequest>,
        ) -> std::result::Result<
            tonic::Response<super::GetUserInfoResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic_prost::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/epic_urc.UrcAuthApi/GetUserInfo",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("epic_urc.UrcAuthApi", "GetUserInfo"));
            self.inner.unary(req, path, codec).await
        }
        pub async fn get_user_id(
            &mut self,
            request: impl tonic::IntoRequest<super::GetUserIdRequest>,
        ) -> std::result::Result<
            tonic::Response<super::GetUserIdResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic_prost::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/epic_urc.UrcAuthApi/GetUserId",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("epic_urc.UrcAuthApi", "GetUserId"));
            self.inner.unary(req, path, codec).await
        }
        pub async fn get_provider_user_id(
            &mut self,
            request: impl tonic::IntoRequest<super::GetProviderUserIdRequest>,
        ) -> std::result::Result<
            tonic::Response<super::GetProviderUserIdResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic_prost::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/epic_urc.UrcAuthApi/GetProviderUserId",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("epic_urc.UrcAuthApi", "GetProviderUserId"));
            self.inner.unary(req, path, codec).await
        }
    }
}
