// SPDX-FileCopyrightText: 2026 Epic Games, Inc.
// SPDX-License-Identifier: MIT
//! Build script for lore-server that:
//! 1. Auto-generates `mod.rs` files for `plugins/` and `hooks/` directories
//! 2. Creates `register_all_plugins()` and `register_all_hooks()` functions
//! 3. Populates environment with build details via vergen

use std::collections::BTreeSet;
use std::error::Error;
use std::fmt::Write as FmtWrite;
use std::fs;
use std::io::Write;
use std::path::Path;

include!("../build-helper.rs");

/// Files to exclude from code generation (infrastructure files).
///
/// These files are part of the plugin/hook infrastructure and are always
/// explicitly declared in the generated mod.rs. They are not auto-discovered.
const EXCLUDED_FILES: &[&str] = &[
    "mod.rs",
    "registry.rs",
    "traits.rs",
    "dispatch.rs",
    "context.rs",
];

/// Modules that require feature flags to compile.
/// Maps module name to required feature flag.
/// Currently empty - all modules are included unconditionally based on their
/// source file existence in the plugins/hooks directories.
const FEATURE_GATED_MODULES: &[(&str, &str)] = &[];

/// Header comment for generated files.
const GENERATED_FILE_HEADER: &str = r#"// ============================================================================
// AUTO-GENERATED FILE - DO NOT EDIT MANUALLY
// ============================================================================
// This file is automatically generated by build.rs during compilation.
// Any manual changes will be overwritten on the next build.
//
// To add a new plugin/hook:
// 1. Create a new .rs file in the appropriate directory (plugins/ or hooks/)
// 2. Implement the required traits and register() function
// 3. Run `cargo build` - this file will be regenerated automatically
// ============================================================================

"#;

fn main() -> Result<(), Box<dyn Error>> {
    println!("cargo:rerun-if-env-changed=LORE_BUILD_VERSION_NAME");

    // Generate mod.rs files for plugins and hooks
    generate_plugins_mod()?;
    generate_hooks_mod()?;

    // Set up rerun-if-changed directives for the directories
    println!("cargo:rerun-if-changed=src/plugins");
    println!("cargo:rerun-if-changed=src/hooks");

    // Compile legacy urc.rpc protos (storage + revision) that the server still serves for
    // backward compatibility but that no client crate links against
    compile_legacy_protos()?;

    // Populate environment with build details
    vergen::Emitter::default()
        .add_instructions(&vergen::BuildBuilder::all_build()?)?
        .add_instructions(&vergen::RustcBuilder::all_rustc()?)?
        .add_instructions(&vergen::SysinfoBuilder::all_sysinfo()?)?
        .add_custom_instructions(&LoreVergen::default())?
        .emit()?;

    Ok(())
}

/// Resolve the `protoc` binary the same way prost-build does: the `PROTOC`
/// environment variable if set, otherwise `protoc` from `PATH`.
fn protoc_path() -> std::path::PathBuf {
    std::env::var_os("PROTOC").map_or_else(
        || std::path::PathBuf::from("protoc"),
        std::path::PathBuf::from,
    )
}

/// Returns true if `protoc` can actually be executed. When it can't, the build
/// falls back to the pregenerated sources checked in under src/legacy/generated.
fn protoc_available() -> bool {
    std::process::Command::new(protoc_path())
        .arg("--version")
        .output()
        .is_ok_and(|output| output.status.success())
}

/// Compile the legacy urc.rpc.{Storage,Revision,Repository,Environment}Service protos that now live in this crate. `urc.model` messages stay in `lore-proto`; `extern_path` redirects generated references there so the types are not re-declared.
fn compile_legacy_protos() -> Result<(), Box<dyn Error>> {
    // Declare the codegen inputs unconditionally so Cargo re-runs this script
    // when PROTOC changes or a watched .proto is edited — even on a build where
    // protoc is missing. Emitting these before the availability check is what
    // lets a fixed PROTOC (or a newly installed protoc plus a .proto edit)
    // recover and regenerate; if they were only emitted after the early return,
    // the protoc-missing run would record no watches and fixing PROTOC alone
    // would never re-run this script.
    println!("cargo:rerun-if-env-changed=PROTOC");
    println!("cargo:rerun-if-changed=src/legacy/proto/storage.proto");
    println!("cargo:rerun-if-changed=src/legacy/proto/revision.proto");
    println!("cargo:rerun-if-changed=src/legacy/proto/repository.proto");
    println!("cargo:rerun-if-changed=src/legacy/proto/environment.proto");
    println!("cargo:rerun-if-changed=../lore-proto/proto/model.proto");

    // protoc is only needed to regenerate these bindings. When it isn't
    // installed, rely on the pregenerated sources committed under
    // src/legacy/generated so the crate still builds.
    if !protoc_available() {
        return Ok(());
    }

    let crate_dir = std::env::var("CARGO_MANIFEST_DIR")?;
    let output_dir = std::path::PathBuf::from(&crate_dir)
        .join("src")
        .join("legacy")
        .join("generated");
    fs::create_dir_all(&output_dir)?;

    let mut config = tonic_prost_build::Config::new();
    config.enable_type_names();
    config.bytes(["."]);
    config.extern_path(".urc.model", "::lore_proto::model");

    tonic_prost_build::configure()
        .out_dir(&output_dir)
        .protoc_arg("--experimental_allow_proto3_optional")
        .compile_with_config(
            config,
            &[
                "./src/legacy/proto/storage.proto",
                "./src/legacy/proto/revision.proto",
                "./src/legacy/proto/repository.proto",
                "./src/legacy/proto/environment.proto",
            ],
            &["./src/legacy/proto", "../lore-proto/proto"],
        )?;

    Ok(())
}

/// Represents a discovered module with optional feature gate.
#[derive(Debug, Clone, PartialEq, Eq, PartialOrd, Ord)]
struct DiscoveredModule {
    name: String,
    feature: Option<String>,
}

impl DiscoveredModule {
    fn new(name: String) -> Self {
        // Check if this module requires a feature flag
        let feature = FEATURE_GATED_MODULES
            .iter()
            .find(|(module, _)| *module == name)
            .map(|(_, feature)| (*feature).to_string());

        Self { name, feature }
    }
}

/// Discovers module names from `.rs` files in a directory.
///
/// Returns a sorted set of modules (without `.rs` extension),
/// excluding infrastructure files defined in `EXCLUDED_FILES`.
/// Feature-gated modules are tagged with their required feature.
fn discover_modules(dir: &Path) -> Result<BTreeSet<DiscoveredModule>, Box<dyn Error>> {
    let mut modules = BTreeSet::new();

    if !dir.exists() {
        return Ok(modules);
    }

    for entry in fs::read_dir(dir)? {
        let entry = entry?;
        let path = entry.path();

        // Only process .rs files
        if path.extension().is_some_and(|ext| ext == "rs")
            && let Some(file_name) = path.file_name().and_then(|n| n.to_str())
        {
            // Skip excluded infrastructure files
            if EXCLUDED_FILES.contains(&file_name) {
                continue;
            }

            // Extract module name (filename without .rs)
            let module_name = file_name.trim_end_matches(".rs");
            modules.insert(DiscoveredModule::new(module_name.to_string()));
        }
    }

    Ok(modules)
}

/// Computes a simple hash of content for idempotency checks.
///
/// Uses a simple FNV-1a hash which is sufficient for detecting content changes.
fn compute_content_hash(content: &str) -> u64 {
    const FNV_OFFSET_BASIS: u64 = 0xcbf29ce484222325;
    const FNV_PRIME: u64 = 0x100000001b3;

    let mut hash = FNV_OFFSET_BASIS;
    for byte in content.bytes() {
        hash ^= byte as u64;
        hash = hash.wrapping_mul(FNV_PRIME);
    }
    hash
}

/// Writes content to a file only if it differs from the existing content.
///
/// This ensures idempotent builds - if the content hasn't changed,
/// the file timestamp remains unchanged and cargo won't trigger unnecessary rebuilds.
fn write_if_changed(path: &Path, content: &str) -> Result<bool, Box<dyn Error>> {
    // Check if file exists and has the same content
    if path.exists() {
        let existing_content = fs::read_to_string(path)?;
        if compute_content_hash(&existing_content) == compute_content_hash(content) {
            // Content is the same, no need to write
            return Ok(false);
        }
    }

    // Write the new content
    let mut file = fs::File::create(path)?;
    file.write_all(content.as_bytes())?;
    Ok(true)
}

/// Generates the mod.rs file for the plugins directory.
fn generate_plugins_mod() -> Result<(), Box<dyn Error>> {
    let plugins_dir = Path::new("src/plugins");
    let mod_file = plugins_dir.join("mod.rs");

    let modules = discover_modules(plugins_dir)?;

    let mut content = String::new();
    content.push_str(GENERATED_FILE_HEADER);

    // Module documentation
    content.push_str(PLUGINS_MOD_DOC);

    // Infrastructure module declarations (always present)
    writeln!(content, "pub mod registry;")?;
    writeln!(content, "pub mod traits;")?;
    writeln!(content)?;

    // Plugin module declarations (discovered)
    if !modules.is_empty() {
        writeln!(content, "// Auto-discovered plugin modules")?;
        for module in &modules {
            if let Some(feature) = &module.feature {
                writeln!(content, "#[cfg(feature = \"{feature}\")]")?;
            }
            writeln!(content, "pub mod {};", module.name)?;
        }
        writeln!(content)?;
    }

    // Re-exports
    writeln!(
        content,
        "// Re-export commonly used items at the module level"
    )?;
    writeln!(content, "pub use registry::PluginRegistry;")?;
    writeln!(content, "pub use traits::ImmutableStorePluginFactory;")?;
    writeln!(content, "pub use traits::LockStorePluginFactory;")?;
    writeln!(content, "pub use traits::MutableStorePluginFactory;")?;
    writeln!(content, "pub use traits::NotificationPlugin;")?;
    writeln!(content, "pub use traits::NotificationPluginContext;")?;
    writeln!(content, "pub use traits::NotificationPluginFactory;")?;
    writeln!(content, "pub use traits::NotificationReceiver;")?;
    writeln!(content, "pub use traits::PluginError;")?;
    writeln!(content, "pub use traits::TopologyPluginFactory;")?;
    writeln!(content)?;

    // Generate register_all_plugins function
    content.push_str(REGISTER_ALL_PLUGINS_DOC);

    if modules.is_empty() {
        writeln!(
            content,
            "    // No plugins discovered - registry will be empty"
        )?;
        writeln!(
            content,
            "    let _ = registry; // Suppress unused variable warning"
        )?;
    } else {
        for module in &modules {
            if let Some(feature) = &module.feature {
                writeln!(content, "    #[cfg(feature = \"{feature}\")]")?;
            }
            writeln!(content, "    {}::register(registry);", module.name)?;
        }
    }
    writeln!(content, "}}")?;

    // Write the file only if content changed
    let changed = write_if_changed(&mod_file, &content)?;
    if changed {
        println!(
            "cargo:info=Generated plugins/mod.rs with {} plugin(s)",
            modules.len()
        );
    }

    Ok(())
}

/// Generates the mod.rs file for the hooks directory.
fn generate_hooks_mod() -> Result<(), Box<dyn Error>> {
    let hooks_dir = Path::new("src/hooks");
    let mod_file = hooks_dir.join("mod.rs");

    let modules = discover_modules(hooks_dir)?;

    let mut content = String::new();
    content.push_str(GENERATED_FILE_HEADER);

    // Module documentation
    content.push_str(HOOKS_MOD_DOC);

    // Infrastructure module declarations (always present)
    writeln!(content, "pub mod context;")?;
    writeln!(content, "pub mod dispatch;")?;
    writeln!(content, "pub mod registry;")?;
    writeln!(content, "pub mod traits;")?;
    writeln!(content)?;

    // Hook module declarations (discovered)
    if !modules.is_empty() {
        writeln!(content, "// Auto-discovered hook modules")?;
        for module in &modules {
            if let Some(feature) = &module.feature {
                writeln!(content, "#[cfg(feature = \"{feature}\")]")?;
            }
            writeln!(content, "pub mod {};", module.name)?;
        }
        writeln!(content)?;
    }

    // Re-exports
    writeln!(
        content,
        "// Re-export commonly used items at the module level"
    )?;
    writeln!(content, "pub use context::HookContext;")?;
    writeln!(content, "pub use context::HookContextBuilder;")?;
    writeln!(content, "pub use dispatch::DEFAULT_POST_HANDLER_TIMEOUT;")?;
    writeln!(content, "pub use dispatch::DEFAULT_PRE_HANDLER_TIMEOUT;")?;
    writeln!(content, "pub use dispatch::HookDispatcher;")?;
    writeln!(content, "pub use registry::HookRegistrationContext;")?;
    writeln!(content, "pub use registry::HookRegistry;")?;
    writeln!(content, "pub use registry::HookSettings;")?;
    writeln!(content, "pub use traits::Hook;")?;
    writeln!(content, "pub use traits::HookError;")?;
    writeln!(content, "pub use traits::HookFactory;")?;
    writeln!(content, "pub use traits::HookPoint;")?;
    writeln!(content, "pub use traits::HookResponse;")?;
    writeln!(content, "pub use traits::StatusCode;")?;
    writeln!(content)?;

    // Generate register_all_hooks function
    content.push_str(REGISTER_ALL_HOOKS_DOC);

    if modules.is_empty() {
        writeln!(
            content,
            "    // No hooks discovered - registry will be empty"
        )?;
        writeln!(
            content,
            "    let _ = (registry, ctx); // Suppress unused variable warnings"
        )?;
    } else {
        for module in &modules {
            if let Some(feature) = &module.feature {
                writeln!(content, "    #[cfg(feature = \"{feature}\")]")?;
            }
            writeln!(content, "    {}::register(registry, ctx);", module.name)?;
        }
    }
    writeln!(content, "}}")?;

    // Add integration tests module
    content.push_str(HOOKS_INTEGRATION_TESTS);

    // Write the file only if content changed
    let changed = write_if_changed(&mod_file, &content)?;
    if changed {
        println!(
            "cargo:info=Generated hooks/mod.rs with {} hook(s)",
            modules.len()
        );
    }

    Ok(())
}

/// Documentation for the plugins module.
const PLUGINS_MOD_DOC: &str = r##"//! Plugin infrastructure for Lore Server modularization.
//!
//! This module provides a compile-time plugin system that supports swappable
//! storage backends and topology discovery mechanisms. The plugin system
//! uses factory traits that can be implemented by different crates and
//! registered at application startup based on compile-time feature flags.
//!
//! # Architecture
//!
//! The plugin system consists of three main components:
//!
//! 1. **Factory Traits** ([`traits`]) - Define the interface for creating plugin instances
//! 2. **Plugin Registry** ([`registry`]) - Central hub for registering and creating plugins
//! 3. **Error Types** ([`PluginError`]) - Error types for plugin operations
//!
//! # Plugin Types
//!
//! The system supports four types of plugins:
//!
//! - **Immutable Store** - Backend for storing immutable data (e.g., local filesystem, S3)
//! - **Mutable Store** - Backend for storing mutable data (e.g., local filesystem, `DynamoDB`)
//! - **Lock Store** - Backend for distributed locking (e.g., local filesystem, `DynamoDB`)
//! - **Topology** - Service discovery mechanism (e.g., fixed list, Consul)
//!
//! # Usage
//!
//! ## Registering Plugins
//!
//! Plugins are typically registered at application startup:
//!
//! ```
//! use lore_server::plugins::PluginRegistry;
//!
//! let mut registry = PluginRegistry::new();
//!
//! // Register all compiled-in plugins (populated by build.rs)
//! lore_server::plugins::register_all_plugins(&mut registry);
//!
//! // List registered plugins
//! let plugins = registry.list_immutable_store_plugins();
//! ```
//!
//! ## Creating Plugin Instances
//!
//! ```
//! use lore_server::plugins::PluginRegistry;
//!
//! let registry = PluginRegistry::new();
//!
//! // Try to create a plugin (would fail if 'local' is not registered)
//! let config: toml::Value = toml::from_str(r#"
//!     path = '/data/store'
//!     max_capacity = 1000000
//! "#).unwrap();
//!
//! // In a real scenario with registered plugins:
//! // let store = registry.create_immutable_store("local", &config)?;
//!
//! // List what's available
//! let available = registry.list_immutable_store_plugins();
//! ```
//!
//! # Error Handling
//!
//! [`PluginError`] is an `error_set` enum with three named variants:
//!
//! - `PluginNotFound` - Requested plugin is not compiled in
//! - `PluginConfigError` - Configuration validation failed
//! - `PluginInitError` - Plugin initialization failed
//!
//! Callers can match via the generated `.is_plugin_not_found()` /
//! `.is_plugin_config_error()` / `.is_plugin_init_error()` accessors.

"##;

/// Documentation for the `register_all_plugins` function.
const REGISTER_ALL_PLUGINS_DOC: &str = r#"/// Registers all compiled-in plugins with the registry.
///
/// This function is auto-generated by `build.rs` and calls each plugin's
/// `register()` function to register its factories with the registry.
///
/// # Arguments
///
/// * `registry` - The plugin registry to register plugins with
///
/// # Example
///
/// ```
/// use lore_server::plugins::PluginRegistry;
///
/// let mut registry = PluginRegistry::new();
/// lore_server::plugins::register_all_plugins(&mut registry);
///
/// // Registry now contains plugins discovered by build.rs
/// // In tests, this may be empty if no plugins are compiled in
/// let stores = registry.list_immutable_store_plugins();
/// ```
pub fn register_all_plugins(registry: &mut PluginRegistry) {
"#;

/// Documentation for the hooks module.
const HOOKS_MOD_DOC: &str = r#"//! Hook infrastructure for Lore Server modularization.
//!
//! This module provides an event-driven hook system that allows code to be
//! executed at specific points in the server lifecycle without modifying
//! core handlers. Hooks can:
//!
//! - Read operation context (repository, branch, user, revision)
//! - Mutate context data for downstream hooks and handlers
//! - Veto operations by returning errors with semantic status codes
//!
//! # Architecture
//!
//! The hook system consists of four main components:
//!
//! 1. **Traits** ([`traits`]) - Core trait definitions ([`Hook`], [`HookFactory`])
//! 2. **Context** ([`context`]) - Operation context passed to hooks ([`HookContext`])
//! 3. **Registry** ([`registry`]) - Factory registration and hook creation ([`HookRegistry`])
//! 4. **Dispatcher** ([`dispatch`]) - Hook execution with isolation ([`HookDispatcher`])
//!
//! # Two-Phase Execution Model
//!
//! The hook system supports a two-phase execution model:
//!
//! 1. **Pre-handler** (synchronous): Called BEFORE the operation
//!    - Can read/modify context
//!    - Can veto/reject by returning `Err(HookError::Rejected)`
//!    - Subject to timeout (default 200ms)
//!    - Panics are caught and isolated
//!
//! 2. **Post-handler** (asynchronous): Called AFTER the operation
//!    - Spawned in separate tokio task
//!    - Does not block the response
//!    - Errors are logged but not propagated
//!
//! # Hook Points
//!
//! Hooks can be triggered at:
//!
//! - [`HookPoint::BranchPush`] - When a branch is pushed to
//! - [`HookPoint::BranchCreate`] - When a new branch is created
//! - [`HookPoint::BranchDelete`] - When a branch is deleted
//! - [`HookPoint::RepositoryCreate`] - When a new repository is created
//! - [`HookPoint::Obliterate`] - When data is obliterated
//!
//! # Status Codes
//!
//! Hooks can reject operations with semantic status codes via [`StatusCode`]:
//!
//! - [`StatusCode::PermissionDenied`] - Policy or authorization violations
//! - [`StatusCode::FailedPrecondition`] - General business rule violations
//! - [`StatusCode::ResourceExhausted`] - Rate limiting, quota exceeded
//! - [`StatusCode::InvalidArgument`] - Validation failures
//! - [`StatusCode::Aborted`] - Conflict/concurrency issues
//!
//! # Usage
//!
//! ## Registering Hooks
//!
//! Hooks are registered at application startup via the auto-generated
//! `register_all_hooks()` function. A [`HookRegistrationContext`] provides
//! runtime dependencies (e.g., notification sender) to hook factories:
//!
//! ```no_run
//! use lore_server::hooks::{HookRegistry, HookRegistrationContext};
//!
//! # fn example(ctx: &HookRegistrationContext) {
//! let mut registry = HookRegistry::new();
//! lore_server::hooks::register_all_hooks(&mut registry, &ctx);
//!
//! // List registered hooks (populated by build.rs auto-discovery)
//! let hooks = registry.list_hooks();
//! # }
//! ```
//!
//! ## Creating Enabled Hooks
//!
//! Enabled hooks are created based on configuration:
//!
//! ```
//! use lore_server::hooks::{HookRegistry, HookSettings};
//! use std::collections::HashMap;
//!
//! let registry = HookRegistry::new();
//! let settings: HashMap<String, HookSettings> = HashMap::new();
//! let enabled_hooks = registry.create_enabled_hooks(&settings).unwrap();
//! // enabled_hooks is empty because no hooks are registered
//! ```
//!
//! ## Creating the Dispatcher
//!
//! The dispatcher executes hooks at runtime:
//!
//! ```
//! use lore_server::hooks::HookDispatcher;
//! use std::time::Duration;
//!
//! // Create from enabled hooks with default timeouts
//! let enabled_hooks = vec![];
//! let dispatcher = HookDispatcher::from_hooks_default(enabled_hooks);
//!
//! // Or create an empty dispatcher directly
//! let dispatcher = HookDispatcher::empty();
//! ```
//!
//! ## Dispatching Hooks (Two-Phase)
//!
//! Hooks are dispatched from request handlers using the two-phase model:
//!
//! ```
//! use lore_server::hooks::{HookContext, HookDispatcher, HookPoint};
//! use lore_revision::lore::{BranchId, RepositoryId};
//!
//! // Create context for the operation
//! let ctx = HookContext::builder()
//!     .correlation_id("correlation-123")
//!     .hook_point(HookPoint::BranchPush)
//!     .repository(RepositoryId::default())
//!     .branch(BranchId::default())
//!     .user("user_id")
//!     .build();
//!
//! // Create dispatcher
//! let dispatcher = HookDispatcher::empty();
//!
//! // Phase 1: Dispatch pre-handlers (synchronous, can veto)
//! // dispatcher.dispatch_pre(HookPoint::BranchPush, &ctx)?;
//!
//! // ... perform the actual operation ...
//!
//! // Phase 2: Spawn post-handlers (asynchronous, non-blocking)
//! // dispatcher.spawn_post(HookPoint::BranchPush, ctx);
//! ```
//!
//! # Implementing Hooks
//!
//! To create a new hook:
//!
//! 1. Create a new file in `src/hooks/` (e.g., `my_hook.rs`)
//! 2. Implement the [`Hook`] trait with `pre_handler()` and/or `post_handler()`
//! 3. Implement a [`HookFactory`] for your hook
//! 4. Add a `register()` function to register the factory
//!
//! ```
//! // src/hooks/my_hook.rs
//! use async_trait::async_trait;
//! use lore_server::hooks::{
//!     Hook, HookContext, HookError, HookFactory, HookPoint, HookRegistrationContext, HookRegistry, StatusCode
//! };
//!
//! struct MyHook {
//!     config_value: String,
//! }
//!
//! #[async_trait]
//! impl Hook for MyHook {
//!     fn name(&self) -> &'static str {
//!         "my_hook"
//!     }
//!
//!     fn hook_points(&self) -> &'static [HookPoint] {
//!         &[HookPoint::BranchPush]
//!     }
//!
//!     fn pre_handler(&self, ctx: &HookContext) -> Result<(), HookError> {
//!         // Validate before operation (can reject)
//!         if ctx.user().map_or(false, |u| u.starts_with("blocked_")) {
//!             return Err(HookError::rejected(
//!                 self.name(),
//!                 "User is blocked",
//!                 StatusCode::PermissionDenied,
//!             ));
//!         }
//!         Ok(())
//!     }
//!
//!     async fn post_handler(&self, ctx: &HookContext) -> Result<(), HookError> {
//!         // Audit logging after operation (non-blocking)
//!         println!("MyHook post-handler: {}", ctx.correlation_id());
//!         Ok(())
//!     }
//! }
//!
//! struct MyHookFactory;
//!
//! impl HookFactory for MyHookFactory {
//!     fn name(&self) -> &'static str {
//!         "my_hook"
//!     }
//!
//!     fn create(&self, config: &toml::Value) -> Result<Box<dyn Hook>, HookError> {
//!         // Parse config and create hook
//!         let config_value = config
//!             .get("value")
//!             .and_then(|v| v.as_str())
//!             .unwrap_or("default")
//!             .to_string();
//!         Ok(Box::new(MyHook { config_value }))
//!     }
//! }
//!
//! pub fn register(registry: &mut HookRegistry, _ctx: &HookRegistrationContext) {
//!     registry.register_hook(Box::new(MyHookFactory));
//! }
//!
//! # fn main() {
//! // Test the factory
//! let factory = MyHookFactory;
//! let config = toml::Value::Table(toml::map::Map::new());
//! let hook = factory.create(&config).unwrap();
//! assert_eq!(hook.name(), "my_hook");
//! # }
//! ```
//!
//! # Error Handling
//!
//! Hook errors are categorized as:
//!
//! - [`HookError::Rejected`] - Hook explicitly rejected/vetoed the operation
//! - [`HookError::ExecutionFailed`] - Hook returned an error (may veto operation)
//! - [`HookError::Timeout`] - Hook exceeded timeout (default 200ms for pre, 30s for post)
//! - [`HookError::Panic`] - Hook panicked (caught and isolated)
//! - [`HookError::ConfigError`] - Hook configuration is invalid
//! - [`HookError::InitError`] - Hook initialization failed
//!
//! All errors include the hook name and relevant context for debugging.
//! Errors are logged with correlation IDs for audit trails.

"#;

/// Documentation for the `register_all_hooks` function.
const REGISTER_ALL_HOOKS_DOC: &str = r#"/// Registers all compiled-in hooks with the registry.
///
/// This function is auto-generated by `build.rs` and calls each hook's
/// `register()` function to register its factory with the registry.
///
/// # Arguments
///
/// * `registry` - The hook registry to register hooks with
/// * `ctx` - Registration context providing runtime dependencies for hook factories
pub fn register_all_hooks(registry: &mut HookRegistry, ctx: &HookRegistrationContext) {
"#;

/// Integration tests for the hooks module (appended to generated mod.rs).
const HOOKS_INTEGRATION_TESTS: &str = r#"
#[cfg(test)]
mod integration_tests {
    use std::sync::Arc;
    use std::sync::atomic::AtomicUsize;
    use std::sync::atomic::Ordering;
    use std::time::Duration;

    use async_trait::async_trait;
    use lore_base::runtime::LORE_CONTEXT;
    use lore_revision::lore::RepositoryId;

    use super::*;

    fn test_execution_context() -> std::sync::Arc<lore_revision::interface::ExecutionContext> {
        crate::util::setup_execution("test", "test".to_string(), "test-user".to_string())
    }

    /// Mock hook for integration testing with two-phase execution
    struct TestHook {
        name: &'static str,
        points: &'static [HookPoint],
        pre_count: Arc<AtomicUsize>,
        post_count: Arc<AtomicUsize>,
    }

    impl TestHook {
        fn new(name: &'static str, points: &'static [HookPoint]) -> Self {
            Self {
                name,
                points,
                pre_count: Arc::new(AtomicUsize::new(0)),
                post_count: Arc::new(AtomicUsize::new(0)),
            }
        }
    }

    #[async_trait]
    impl Hook for TestHook {
        fn name(&self) -> &'static str {
            self.name
        }

        fn hook_points(&self) -> &'static [HookPoint] {
            self.points
        }

        fn pre_handler(&self, _ctx: &HookContext) -> Result<(), HookError> {
            self.pre_count.fetch_add(1, Ordering::SeqCst);
            Ok(())
        }

        async fn post_handler(&self, _ctx: &HookContext) -> Result<(), HookError> {
            self.post_count.fetch_add(1, Ordering::SeqCst);
            Ok(())
        }
    }

    struct TestHookFactory {
        name: &'static str,
        points: &'static [HookPoint],
    }

    impl HookFactory for TestHookFactory {
        fn name(&self) -> &'static str {
            self.name
        }

        fn create(&self, _config: &toml::Value) -> Result<Box<dyn Hook>, HookError> {
            Ok(Box::new(TestHook::new(self.name, self.points)))
        }
    }

    #[test]
    fn test_full_workflow() {
        // 1. Create registry
        let mut registry = HookRegistry::new();

        // 2. Register hook factories
        registry.register_hook(Box::new(TestHookFactory {
            name: "test_hook",
            points: &[HookPoint::BranchPush, HookPoint::BranchCreate],
        }));

        // 3. Verify registration
        assert!(registry.has_hook("test_hook"));
        assert_eq!(registry.list_hooks().len(), 1);
    }

    #[tokio::test]
    async fn test_end_to_end_two_phase_dispatch() {
        LORE_CONTEXT
            .scope(test_execution_context(), async {
                // 1. Create registry and register hooks
                let mut registry = HookRegistry::new();
                registry.register_hook(Box::new(TestHookFactory {
                    name: "e2e_hook",
                    points: &[HookPoint::BranchPush],
                }));

                // 2. Create enabled hooks from settings
                let mut settings = std::collections::HashMap::new();
                settings.insert(
                    "e2e_hook".to_string(),
                    HookSettings {
                        enabled: true,
                        config: toml::Value::Table(toml::map::Map::new()),
                    },
                );

                let enabled_hooks = registry.create_enabled_hooks(&settings).unwrap();
                assert_eq!(enabled_hooks.len(), 1);

                // 3. Create dispatcher with default timeouts
                let dispatcher = HookDispatcher::from_hooks_default(enabled_hooks);
                assert!(dispatcher.has_hooks(HookPoint::BranchPush));

                // 4. Create context
                let ctx = HookContext::builder()
                    .correlation_id("e2e-test-123")
                    .hook_point(HookPoint::BranchPush)
                    .repository(RepositoryId::default())
                    .user("test_user")
                    .build();

                // 5. Phase 1: Dispatch pre-handlers (synchronous)
                let result = dispatcher.dispatch_pre(HookPoint::BranchPush, &ctx);
                assert!(result.is_ok());

                // 6. Phase 2: Spawn post-handlers (asynchronous)
                dispatcher.spawn_post(HookPoint::BranchPush, ctx);

                // Give post-handlers time to execute
                tokio::time::sleep(Duration::from_millis(50)).await;
            })
            .await;
    }

    #[tokio::test]
    async fn test_hook_veto_workflow() {
        LORE_CONTEXT
            .scope(test_execution_context(), async {
                struct VetoHook;

                #[async_trait]
                impl Hook for VetoHook {
                    fn name(&self) -> &'static str {
                        "veto"
                    }

                    fn hook_points(&self) -> &'static [HookPoint] {
                        &[HookPoint::BranchPush]
                    }

                    fn pre_handler(&self, ctx: &HookContext) -> Result<(), HookError> {
                        // Veto operations from blocked users
                        if let Some(user) = ctx.user()
                            && user.starts_with("blocked_")
                        {
                            return Err(HookError::rejected(
                                self.name(),
                                format!("User '{user}' is blocked"),
                                StatusCode::PermissionDenied,
                            ));
                        }
                        Ok(())
                    }
                }

                struct VetoHookFactory;

                impl HookFactory for VetoHookFactory {
                    fn name(&self) -> &'static str {
                        "veto"
                    }

                    fn create(&self, _config: &toml::Value) -> Result<Box<dyn Hook>, HookError> {
                        Ok(Box::new(VetoHook))
                    }
                }

                // Setup
                let mut registry = HookRegistry::new();
                registry.register_hook(Box::new(VetoHookFactory));

                let mut settings = std::collections::HashMap::new();
                settings.insert(
                    "veto".to_string(),
                    HookSettings {
                        enabled: true,
                        config: toml::Value::Table(toml::map::Map::new()),
                    },
                );

                let enabled_hooks = registry.create_enabled_hooks(&settings).unwrap();
                let dispatcher = HookDispatcher::from_hooks_default(enabled_hooks);

                // Test: Allowed user
                let allowed_ctx = HookContext::builder()
                    .correlation_id("allowed")
                    .hook_point(HookPoint::BranchPush)
                    .repository(RepositoryId::default())
                    .user("normal_user")
                    .build();

                let result = dispatcher.dispatch_pre(HookPoint::BranchPush, &allowed_ctx);
                assert!(result.is_ok());

                // Test: Blocked user
                let blocked_ctx = HookContext::builder()
                    .correlation_id("blocked")
                    .hook_point(HookPoint::BranchPush)
                    .repository(RepositoryId::default())
                    .user("blocked_user")
                    .build();

                let result = dispatcher.dispatch_pre(HookPoint::BranchPush, &blocked_ctx);
                assert!(result.is_err());

                match result.unwrap_err() {
                    HookError::Rejected {
                        hook_name,
                        message,
                        status,
                    } => {
                        assert_eq!(hook_name, "veto");
                        assert!(message.contains("blocked_user"));
                        assert_eq!(status, StatusCode::PermissionDenied);
                    }
                    _ => panic!("Expected Rejected error"),
                }
            })
            .await;
    }
}
"#;

// Tests are run during the normal test phase via `cargo test -p lore-server`
// The build.rs logic is tested through the actual build process and integration tests.
// Unit tests for the helper functions are kept minimal as they're validated
// by the build process itself.
#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_discover_modules_nonexistent_dir() {
        let modules = discover_modules(Path::new("/nonexistent/path/that/does/not/exist")).unwrap();
        assert!(modules.is_empty());
    }

    #[test]
    fn test_compute_content_hash_deterministic() {
        let content = "Hello, World!";
        let hash1 = compute_content_hash(content);
        let hash2 = compute_content_hash(content);
        assert_eq!(hash1, hash2);
    }

    #[test]
    fn test_compute_content_hash_different_content() {
        let hash1 = compute_content_hash("Hello");
        let hash2 = compute_content_hash("World");
        assert_ne!(hash1, hash2);
    }

    #[test]
    fn test_excluded_files_list() {
        // Verify our exclusion list contains expected infrastructure files
        assert!(EXCLUDED_FILES.contains(&"mod.rs"));
        assert!(EXCLUDED_FILES.contains(&"registry.rs"));
        assert!(EXCLUDED_FILES.contains(&"traits.rs"));
        assert!(EXCLUDED_FILES.contains(&"dispatch.rs"));
        assert!(EXCLUDED_FILES.contains(&"context.rs"));
    }

    #[test]
    fn test_generated_file_header_contains_warning() {
        assert!(GENERATED_FILE_HEADER.contains("AUTO-GENERATED"));
        assert!(GENERATED_FILE_HEADER.contains("DO NOT EDIT"));
        assert!(GENERATED_FILE_HEADER.contains("build.rs"));
    }
}
